version: '3.1'

networks:
  hyper-task-manager-network:
volumes:
  mongo-data:

services:
  mongodb:
    image: mongo:6.0.8
    container_name: hyper-mongo
    ports:
      - '27027:27017'
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - hyper-task-manager-network
    volumes:
      - mongo-data:/data/db

  hyper-service:
    container_name: hyper-task-manager
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_HOST_NAME: mongodb
      MONGO_PORT_NUMBER: 27017
    env_file:
      - .env
    ports:
      - '8000:8000'
    networks:
      - hyper-task-manager-network
    depends_on:
      - mongodb
